name: flutter_mirai_sample
description: "Sample application using mirai framework."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mirai: ^0.8.0
  freezed_annotation: ^2.4.4
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/json/
